// Script to seed sample products into the database
// Run with: node scripts/seedProducts.js

import mongoose from 'mongoose';
import { config } from 'dotenv';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import Product from '../models/Product.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Load environment variables from .env.local
config({ path: join(__dirname, '..', '.env.local') });

const sampleProducts = [
  // ========== FOOD CATEGORY ==========
  {
    name: 'Premium Dog Food - Chicken & Rice',
    description: 'High-quality dry dog food with real chicken and brown rice. Perfect for adult dogs.',
    price: 45.99,
    category: 'food',
    subcategory: 'dry-food',
    petType: ['dog'],
    images: ['https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=500'],
    stock: 50,
    sku: 'DOG-FOOD-001',
    brand: 'Lumberjacks Pet Care Premium',
    rating: 4.5,
    featured: true,
    subscriptionEligible: true,
  },
  {
    name: 'Grain-Free Dog Food - Salmon & Sweet Potato',
    description: 'Premium grain-free formula with wild-caught salmon. Ideal for dogs with food sensitivities.',
    price: 52.99,
    category: 'food',
    subcategory: 'dry-food',
    petType: ['dog'],
    images: ['https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=500'],
    stock: 45,
    sku: 'DOG-FOOD-002',
    brand: 'Natural Choice',
    rating: 4.7,
    featured: true,
    subscriptionEligible: true,
  },
  {
    name: 'Puppy Food - Growth Formula',
    description: 'Specially formulated for puppies to support healthy growth and development.',
    price: 38.99,
    category: 'food',
    subcategory: 'puppy-food',
    petType: ['dog'],
    images: ['https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=500'],
    stock: 55,
    sku: 'DOG-FOOD-003',
    brand: 'GrowthPlus',
    rating: 4.8,
    featured: true,
    subscriptionEligible: true,
  },
  {
    name: 'Senior Dog Food - Joint Support',
    description: 'Formulated for senior dogs with glucosamine and chondroitin for joint health.',
    price: 48.99,
    category: 'food',
    subcategory: 'senior-food',
    petType: ['dog'],
    images: ['https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=500'],
    stock: 40,
    sku: 'DOG-FOOD-004',
    brand: 'SeniorCare',
    rating: 4.6,
    featured: false,
    subscriptionEligible: true,
  },
  {
    name: 'Small Breed Dog Food - Chicken',
    description: 'Specially sized kibble for small breed dogs. High protein, easy to digest.',
    price: 42.99,
    category: 'food',
    subcategory: 'dry-food',
    petType: ['dog'],
    images: ['https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=500'],
    stock: 60,
    sku: 'DOG-FOOD-005',
    brand: 'TinyBites',
    rating: 4.5,
    featured: false,
    subscriptionEligible: true,
  },
  {
    name: 'Large Breed Dog Food - Lamb & Rice',
    description: 'Formulated for large breed dogs. Supports healthy bone and joint development.',
    price: 54.99,
    category: 'food',
    subcategory: 'dry-food',
    petType: ['dog'],
    images: ['https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=500'],
    stock: 35,
    sku: 'DOG-FOOD-006',
    brand: 'BigDog',
    rating: 4.7,
    featured: false,
    subscriptionEligible: true,
  },
  {
    name: 'Grain-Free Cat Food - Salmon',
    description: 'Premium grain-free wet cat food with real salmon. Rich in protein and omega-3.',
    price: 32.99,
    category: 'food',
    subcategory: 'wet-food',
    petType: ['cat'],
    images: ['https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=500'],
    stock: 65,
    sku: 'CAT-FOOD-001',
    brand: 'Natural Choice',
    rating: 4.7,
    featured: true,
    subscriptionEligible: true,
  },
  {
    name: 'Dry Cat Food - Chicken & Turkey',
    description: 'Complete nutrition dry cat food with real chicken and turkey. Balanced for all life stages.',
    price: 28.99,
    category: 'food',
    subcategory: 'dry-food',
    petType: ['cat'],
    images: ['https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=500'],
    stock: 70,
    sku: 'CAT-FOOD-002',
    brand: 'FelineFeast',
    rating: 4.6,
    featured: true,
    subscriptionEligible: true,
  },
  {
    name: 'Kitten Food - Growth Formula',
    description: 'Specially formulated for kittens. High in protein and DHA for brain development.',
    price: 26.99,
    category: 'food',
    subcategory: 'kitten-food',
    petType: ['cat'],
    images: ['https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=500'],
    stock: 50,
    sku: 'CAT-FOOD-003',
    brand: 'KittenCare',
    rating: 4.8,
    featured: true,
    subscriptionEligible: true,
  },
  {
    name: 'Indoor Cat Food - Weight Management',
    description: 'Low-calorie formula for indoor cats. Helps maintain healthy weight.',
    price: 29.99,
    category: 'food',
    subcategory: 'dry-food',
    petType: ['cat'],
    images: ['https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=500'],
    stock: 55,
    sku: 'CAT-FOOD-004',
    brand: 'IndoorCat',
    rating: 4.5,
    featured: false,
    subscriptionEligible: true,
  },
  {
    name: 'Bird Seed Mix - Premium Blend',
    description: 'Nutritious seed mix for all types of birds. Contains sunflower seeds, millet, and more.',
    price: 15.99,
    category: 'food',
    subcategory: 'bird-food',
    petType: ['bird'],
    images: ['https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=500'],
    stock: 80,
    sku: 'BIRD-FOOD-001',
    brand: 'FeatherFeed',
    rating: 4.6,
    featured: false,
    subscriptionEligible: true,
  },
  {
    name: 'Parrot Pellets - Complete Nutrition',
    description: 'Nutritionally complete pellets for parrots. Fortified with vitamins and minerals.',
    price: 18.99,
    category: 'food',
    subcategory: 'bird-food',
    petType: ['bird'],
    images: ['https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=500'],
    stock: 45,
    sku: 'BIRD-FOOD-002',
    brand: 'ParrotPro',
    rating: 4.7,
    featured: false,
    subscriptionEligible: true,
  },
  {
    name: 'Small Animal Pellets - Complete Nutrition',
    description: 'Balanced nutrition pellets for rabbits, guinea pigs, and hamsters.',
    price: 12.99,
    category: 'food',
    subcategory: 'small-animal-food',
    petType: ['small-animal'],
    images: ['https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=500'],
    stock: 90,
    sku: 'SMALL-FOOD-001',
    brand: 'TinyBites',
    rating: 4.4,
    featured: false,
    subscriptionEligible: true,
  },
  {
    name: 'Rabbit Hay - Timothy Hay',
    description: 'Premium timothy hay for rabbits. High fiber, promotes dental health.',
    price: 9.99,
    category: 'food',
    subcategory: 'hay',
    petType: ['small-animal'],
    images: ['https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=500'],
    stock: 100,
    sku: 'SMALL-FOOD-002',
    brand: 'HayFresh',
    rating: 4.6,
    featured: false,
    subscriptionEligible: true,
  },
  
  // ========== TOYS CATEGORY ==========
  {
    name: 'Interactive Cat Toy - Feather Wand',
    description: 'Engaging feather wand toy to keep your cat active and entertained.',
    price: 12.99,
    category: 'toys',
    subcategory: 'interactive',
    petType: ['cat'],
    images: ['https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=500'],
    stock: 100,
    sku: 'CAT-TOY-001',
    brand: 'Playful Paws',
    rating: 4.8,
    featured: true,
    subscriptionEligible: true,
  },
  {
    name: 'Cat Laser Pointer - Red Dot',
    description: 'Interactive laser pointer for cats. Great for exercise and playtime.',
    price: 8.99,
    category: 'toys',
    subcategory: 'interactive',
    petType: ['cat'],
    images: ['https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=500'],
    stock: 120,
    sku: 'CAT-TOY-002',
    brand: 'LaserFun',
    rating: 4.7,
    featured: false,
    subscriptionEligible: true,
  },
  {
    name: 'Catnip Mouse Toy - 2 Pack',
    description: 'Adorable mouse toys filled with premium catnip to keep cats entertained.',
    price: 6.99,
    category: 'toys',
    subcategory: 'catnip',
    petType: ['cat'],
    images: ['https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=500'],
    stock: 150,
    sku: 'CAT-TOY-003',
    brand: 'CatnipCo',
    rating: 4.9,
    featured: true,
    subscriptionEligible: true,
  },
  {
    name: 'Cat Scratching Ball - Interactive',
    description: 'Ball with bell inside that cats love to bat around. Encourages play.',
    price: 5.99,
    category: 'toys',
    subcategory: 'balls',
    petType: ['cat'],
    images: ['https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=500'],
    stock: 130,
    sku: 'CAT-TOY-004',
    brand: 'PlayBall',
    rating: 4.5,
    featured: false,
    subscriptionEligible: true,
  },
  {
    name: 'Dog Rope Toy - Tug of War',
    description: 'Durable rope toy perfect for interactive play and dental health.',
    price: 9.99,
    category: 'toys',
    subcategory: 'interactive',
    petType: ['dog'],
    images: ['https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=500'],
    stock: 85,
    sku: 'DOG-TOY-001',
    brand: 'TugMaster',
    rating: 4.6,
    featured: false,
    subscriptionEligible: true,
  },
  {
    name: 'Dog Tennis Ball Set - 3 Pack',
    description: 'Classic tennis balls for fetch and outdoor play. Durable and bouncy.',
    price: 7.99,
    category: 'toys',
    subcategory: 'balls',
    petType: ['dog'],
    images: ['https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=500'],
    stock: 120,
    sku: 'DOG-TOY-002',
    brand: 'FetchPro',
    rating: 4.7,
    featured: false,
    subscriptionEligible: true,
  },
  {
    name: 'Dog Puzzle Toy - Treat Dispenser',
    description: 'Interactive puzzle toy that dispenses treats. Keeps dogs mentally stimulated.',
    price: 19.99,
    category: 'toys',
    subcategory: 'puzzle',
    petType: ['dog'],
    images: ['https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=500'],
    stock: 60,
    sku: 'DOG-TOY-003',
    brand: 'BrainGames',
    rating: 4.8,
    featured: true,
    subscriptionEligible: true,
  },
  {
    name: 'Dog Frisbee - Durable',
    description: 'High-quality frisbee for outdoor play. Weather-resistant and long-lasting.',
    price: 11.99,
    category: 'toys',
    subcategory: 'outdoor',
    petType: ['dog'],
    images: ['https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=500'],
    stock: 75,
    sku: 'DOG-TOY-004',
    brand: 'FrisbeePro',
    rating: 4.6,
    featured: false,
    subscriptionEligible: false,
  },
  {
    name: 'Dog Chew Bone - Natural',
    description: 'Natural bone for dogs to chew. Promotes dental health and satisfies chewing instinct.',
    price: 14.99,
    category: 'toys',
    subcategory: 'chew',
    petType: ['dog'],
    images: ['https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=500'],
    stock: 90,
    sku: 'DOG-TOY-005',
    brand: 'NaturalChew',
    rating: 4.5,
    featured: false,
    subscriptionEligible: true,
  },
  {
    name: 'Small Animal Exercise Wheel',
    description: 'Quiet exercise wheel for hamsters, gerbils, and other small pets.',
    price: 22.99,
    category: 'toys',
    subcategory: 'exercise',
    petType: ['small-animal'],
    images: ['https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=500'],
    stock: 40,
    sku: 'SMALL-TOY-001',
    brand: 'ActivePets',
    rating: 4.5,
    featured: false,
    subscriptionEligible: false,
  },
  {
    name: 'Hamster Tunnel Set - 5 Pieces',
    description: 'Colorful tunnel set for hamsters and gerbils. Encourages exploration and exercise.',
    price: 16.99,
    category: 'toys',
    subcategory: 'tunnels',
    petType: ['small-animal'],
    images: ['https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=500'],
    stock: 50,
    sku: 'SMALL-TOY-002',
    brand: 'TunnelFun',
    rating: 4.4,
    featured: false,
    subscriptionEligible: false,
  },
  {
    name: 'Bird Mirror Toy - Colorful',
    description: 'Safe mirror toy for birds. Encourages interaction and play.',
    price: 7.99,
    category: 'toys',
    subcategory: 'interactive',
    petType: ['bird'],
    images: ['https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=500'],
    stock: 65,
    sku: 'BIRD-TOY-001',
    brand: 'BirdPlay',
    rating: 4.3,
    featured: false,
    subscriptionEligible: false,
  },
  {
    name: 'Bird Swing - Natural Wood',
    description: 'Natural wood swing for bird cages. Provides exercise and entertainment.',
    price: 9.99,
    category: 'toys',
    subcategory: 'swings',
    petType: ['bird'],
    images: ['https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=500'],
    stock: 55,
    sku: 'BIRD-TOY-002',
    brand: 'NaturalSwing',
    rating: 4.5,
    featured: false,
    subscriptionEligible: false,
  },
  
  // ========== GROOMING CATEGORY ==========
  {
    name: 'Dog Grooming Brush - Self-Cleaning',
    description: 'Professional grooming brush that removes loose hair and reduces shedding.',
    price: 18.99,
    category: 'grooming',
    subcategory: 'brushes',
    petType: ['dog'],
    images: ['https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=500'],
    stock: 75,
    sku: 'DOG-GROOM-001',
    brand: 'GroomPro',
    rating: 4.6,
    featured: false,
    subscriptionEligible: true,
  },
  {
    name: 'Cat Grooming Glove',
    description: 'Gentle grooming glove that removes loose fur while petting your cat.',
    price: 14.99,
    category: 'grooming',
    subcategory: 'brushes',
    petType: ['cat'],
    images: ['https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=500'],
    stock: 60,
    sku: 'CAT-GROOM-001',
    brand: 'SoftTouch',
    rating: 4.5,
    featured: false,
    subscriptionEligible: true,
  },
  {
    name: 'Pet Shampoo - Oatmeal & Aloe',
    description: 'Gentle shampoo for sensitive skin. Soothes and moisturizes while cleaning.',
    price: 11.99,
    category: 'grooming',
    subcategory: 'shampoo',
    petType: ['dog', 'cat'],
    images: ['https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=500'],
    stock: 95,
    sku: 'GROOM-SHAMPOO-001',
    brand: 'GentleCare',
    rating: 4.7,
    featured: true,
    subscriptionEligible: true,
  },
  {
    name: 'Deodorizing Shampoo - Fresh Scent',
    description: 'Long-lasting fresh scent shampoo. Eliminates odors between baths.',
    price: 13.99,
    category: 'grooming',
    subcategory: 'shampoo',
    petType: ['dog'],
    images: ['https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=500'],
    stock: 80,
    sku: 'GROOM-SHAMPOO-002',
    brand: 'FreshPet',
    rating: 4.6,
    featured: false,
    subscriptionEligible: true,
  },
  {
    name: 'Nail Clippers - Professional Grade',
    description: 'Sharp, precision nail clippers for dogs and cats. Includes safety guard.',
    price: 16.99,
    category: 'grooming',
    subcategory: 'nail-care',
    petType: ['dog', 'cat'],
    images: ['https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=500'],
    stock: 55,
    sku: 'GROOM-NAIL-001',
    brand: 'PrecisionGroom',
    rating: 4.6,
    featured: false,
    subscriptionEligible: false,
  },
  {
    name: 'Ear Cleaner - Gentle Formula',
    description: 'Gentle ear cleaning solution for dogs and cats. Removes wax and debris safely.',
    price: 9.99,
    category: 'grooming',
    subcategory: 'ear-care',
    petType: ['dog', 'cat'],
    images: ['https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=500'],
    stock: 70,
    sku: 'GROOM-EAR-001',
    brand: 'EarCare',
    rating: 4.5,
    featured: false,
    subscriptionEligible: true,
  },
  {
    name: 'Toothbrush & Toothpaste Set',
    description: 'Complete dental care set. Includes brush and enzymatic toothpaste.',
    price: 12.99,
    category: 'grooming',
    subcategory: 'dental',
    petType: ['dog', 'cat'],
    images: ['https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=500'],
    stock: 65,
    sku: 'GROOM-DENTAL-001',
    brand: 'DentalCare',
    rating: 4.7,
    featured: true,
    subscriptionEligible: true,
  },
  {
    name: 'Deshedding Tool - Undercoat Rake',
    description: 'Removes loose undercoat hair. Reduces shedding by up to 90%.',
    price: 21.99,
    category: 'grooming',
    subcategory: 'brushes',
    petType: ['dog'],
    images: ['https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=500'],
    stock: 45,
    sku: 'DOG-GROOM-002',
    brand: 'ShedMaster',
    rating: 4.8,
    featured: true,
    subscriptionEligible: true,
  },
  
  // ========== HEALTH CATEGORY ==========
  {
    name: 'Dog Health Supplements - Multivitamin',
    description: 'Complete multivitamin supplement for dogs of all ages. Supports overall health.',
    price: 24.99,
    category: 'health',
    subcategory: 'supplements',
    petType: ['dog'],
    images: ['https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=500'],
    stock: 60,
    sku: 'DOG-HEALTH-001',
    brand: 'VetCare',
    rating: 4.9,
    featured: true,
    subscriptionEligible: true,
  },
  {
    name: 'Cat Hairball Remedy - Gel',
    description: 'Prevents and treats hairballs in cats. Easy-to-administer gel formula.',
    price: 13.99,
    category: 'health',
    subcategory: 'hairball',
    petType: ['cat'],
    images: ['https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=500'],
    stock: 70,
    sku: 'CAT-HEALTH-001',
    brand: 'HairballFree',
    rating: 4.5,
    featured: false,
    subscriptionEligible: true,
  },
  {
    name: 'Flea & Tick Prevention - Monthly Treatment',
    description: 'Monthly topical treatment to prevent fleas and ticks. Safe and effective.',
    price: 28.99,
    category: 'health',
    subcategory: 'parasite-control',
    petType: ['dog', 'cat'],
    images: ['https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=500'],
    stock: 50,
    sku: 'HEALTH-FLEA-001',
    brand: 'ProtectPet',
    rating: 4.8,
    featured: true,
    subscriptionEligible: true,
  },
  {
    name: 'Joint Support Chews - Senior Dogs',
    description: 'Glucosamine and chondroitin chews to support joint health in senior dogs.',
    price: 19.99,
    category: 'health',
    subcategory: 'joint-care',
    petType: ['dog'],
    images: ['https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=500'],
    stock: 45,
    sku: 'DOG-HEALTH-002',
    brand: 'JointCare',
    rating: 4.7,
    featured: false,
    subscriptionEligible: true,
  },
  {
    name: 'Probiotics for Dogs - Digestive Health',
    description: 'Probiotic supplement to support healthy digestion and immune system.',
    price: 22.99,
    category: 'health',
    subcategory: 'digestive',
    petType: ['dog'],
    images: ['https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=500'],
    stock: 55,
    sku: 'DOG-HEALTH-003',
    brand: 'DigestPro',
    rating: 4.6,
    featured: false,
    subscriptionEligible: true,
  },
  {
    name: 'Cat Calming Supplement - Stress Relief',
    description: 'Natural calming supplement for cats. Reduces anxiety and stress.',
    price: 16.99,
    category: 'health',
    subcategory: 'calming',
    petType: ['cat'],
    images: ['https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=500'],
    stock: 50,
    sku: 'CAT-HEALTH-002',
    brand: 'CalmCat',
    rating: 4.5,
    featured: false,
    subscriptionEligible: true,
  },
  {
    name: 'Worm Prevention - Monthly Tablet',
    description: 'Monthly deworming tablet for dogs and cats. Prevents common parasites.',
    price: 15.99,
    category: 'health',
    subcategory: 'parasite-control',
    petType: ['dog', 'cat'],
    images: ['https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=500'],
    stock: 65,
    sku: 'HEALTH-WORM-001',
    brand: 'WormFree',
    rating: 4.7,
    featured: false,
    subscriptionEligible: true,
  },
  {
    name: 'Skin & Coat Supplement - Omega-3',
    description: 'Omega-3 fatty acids for healthy skin and shiny coat. For dogs and cats.',
    price: 18.99,
    category: 'health',
    subcategory: 'skin-coat',
    petType: ['dog', 'cat'],
    images: ['https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=500'],
    stock: 58,
    sku: 'HEALTH-OMEGA-001',
    brand: 'ShinyCoat',
    rating: 4.8,
    featured: true,
    subscriptionEligible: true,
  },
  
  // ========== TREATS CATEGORY ==========
  {
    name: 'Cat Dental Health Treats',
    description: 'Delicious treats that help clean teeth and freshen breath. Made with natural ingredients.',
    price: 8.99,
    category: 'treats',
    subcategory: 'dental',
    petType: ['cat'],
    images: ['https://images.unsplash.com/photo-1574158622682-e40e69881006?w=500'],
    stock: 200,
    sku: 'CAT-TREAT-001',
    brand: 'Healthy Bites',
    rating: 4.7,
    featured: true,
    subscriptionEligible: true,
  },
  {
    name: 'Dog Training Treats - Small Bites',
    description: 'Perfect size for training. High-value treats that dogs love.',
    price: 6.99,
    category: 'treats',
    subcategory: 'training',
    petType: ['dog'],
    images: ['https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=500'],
    stock: 180,
    sku: 'DOG-TREAT-001',
    brand: 'TrainSmart',
    rating: 4.8,
    featured: true,
    subscriptionEligible: true,
  },
  {
    name: 'Freeze-Dried Chicken Treats',
    description: 'Single-ingredient freeze-dried chicken. Pure protein, no additives.',
    price: 12.99,
    category: 'treats',
    subcategory: 'natural',
    petType: ['dog', 'cat'],
    images: ['https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=500'],
    stock: 140,
    sku: 'TREAT-CHICKEN-001',
    brand: 'PureProtein',
    rating: 4.9,
    featured: true,
    subscriptionEligible: true,
  },
  {
    name: 'Bird Treat Sticks - Honey & Seeds',
    description: 'Nutritious treat sticks for birds. Made with honey and premium seeds.',
    price: 4.99,
    category: 'treats',
    subcategory: 'bird-treats',
    petType: ['bird'],
    images: ['https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=500'],
    stock: 110,
    sku: 'BIRD-TREAT-001',
    brand: 'SweetBeaks',
    rating: 4.6,
    featured: false,
    subscriptionEligible: true,
  },
  {
    name: 'Dog Jerky Treats - Beef',
    description: 'Real beef jerky treats for dogs. High protein, low fat, all natural.',
    price: 15.99,
    category: 'treats',
    subcategory: 'jerky',
    petType: ['dog'],
    images: ['https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=500'],
    stock: 95,
    sku: 'DOG-TREAT-002',
    brand: 'JerkyPro',
    rating: 4.7,
    featured: false,
    subscriptionEligible: true,
  },
  {
    name: 'Cat Tuna Treats - Soft & Moist',
    description: 'Soft, moist treats made with real tuna. Cats go crazy for these!',
    price: 7.99,
    category: 'treats',
    subcategory: 'soft',
    petType: ['cat'],
    images: ['https://images.unsplash.com/photo-1574158622682-e40e69881006?w=500'],
    stock: 160,
    sku: 'CAT-TREAT-002',
    brand: 'TunaTreats',
    rating: 4.9,
    featured: true,
    subscriptionEligible: true,
  },
  {
    name: 'Puppy Training Treats - Chicken',
    description: 'Small, soft treats perfect for puppies. Easy to chew and digest.',
    price: 5.99,
    category: 'treats',
    subcategory: 'training',
    petType: ['dog'],
    images: ['https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=500'],
    stock: 175,
    sku: 'DOG-TREAT-003',
    brand: 'PuppyBites',
    rating: 4.8,
    featured: false,
    subscriptionEligible: true,
  },
  {
    name: 'Dental Chews - Large Dogs',
    description: 'Large dental chews that clean teeth and freshen breath. For dogs 50+ lbs.',
    price: 17.99,
    category: 'treats',
    subcategory: 'dental',
    petType: ['dog'],
    images: ['https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=500'],
    stock: 70,
    sku: 'DOG-TREAT-004',
    brand: 'DentalChew',
    rating: 4.6,
    featured: false,
    subscriptionEligible: true,
  },
  
  // ========== ACCESSORIES CATEGORY ==========
  {
    name: 'Pet Carrier - Airline Approved',
    description: 'Comfortable and secure pet carrier for travel. Meets airline requirements.',
    price: 59.99,
    category: 'accessories',
    subcategory: 'travel',
    petType: ['dog', 'cat', 'small-animal'],
    images: ['https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=500'],
    stock: 30,
    sku: 'PET-ACC-001',
    brand: 'TravelSafe',
    rating: 4.4,
    featured: false,
    subscriptionEligible: false,
  },
  {
    name: 'Dog Leash - Retractable 16ft',
    description: 'Durable retractable leash with comfortable grip. Perfect for walks.',
    price: 24.99,
    category: 'accessories',
    subcategory: 'leashes',
    petType: ['dog'],
    images: ['https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=500'],
    stock: 65,
    sku: 'DOG-ACC-001',
    brand: 'WalkEasy',
    rating: 4.5,
    featured: false,
    subscriptionEligible: false,
  },
  {
    name: 'Cat Scratching Post - 32 inches',
    description: 'Tall scratching post with sisal rope. Helps protect furniture.',
    price: 34.99,
    category: 'accessories',
    subcategory: 'furniture',
    petType: ['cat'],
    images: ['https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=500'],
    stock: 40,
    sku: 'CAT-ACC-001',
    brand: 'ScratchMaster',
    rating: 4.6,
    featured: true,
    subscriptionEligible: false,
  },
  {
    name: 'Pet Food Bowl Set - Stainless Steel',
    description: 'Durable stainless steel bowls. Includes food and water bowls.',
    price: 15.99,
    category: 'accessories',
    subcategory: 'bowls',
    petType: ['dog', 'cat'],
    images: ['https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=500'],
    stock: 85,
    sku: 'ACC-BOWL-001',
    brand: 'SteelPet',
    rating: 4.7,
    featured: false,
    subscriptionEligible: false,
  },
  {
    name: 'Dog Collar - Adjustable Nylon',
    description: 'Comfortable adjustable nylon collar with quick-release buckle.',
    price: 9.99,
    category: 'accessories',
    subcategory: 'collars',
    petType: ['dog'],
    images: ['https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=500'],
    stock: 100,
    sku: 'DOG-ACC-002',
    brand: 'ComfortFit',
    rating: 4.5,
    featured: false,
    subscriptionEligible: false,
  },
  {
    name: 'Bird Cage Accessories - Perch Set',
    description: 'Natural wood perches in various sizes for bird cages.',
    price: 12.99,
    category: 'accessories',
    subcategory: 'cage-accessories',
    petType: ['bird'],
    images: ['https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=500'],
    stock: 55,
    sku: 'BIRD-ACC-001',
    brand: 'NaturalPerch',
    rating: 4.4,
    featured: false,
    subscriptionEligible: false,
  },
  {
    name: 'Dog Harness - No-Pull',
    description: 'Comfortable no-pull harness. Prevents pulling and provides better control.',
    price: 29.99,
    category: 'accessories',
    subcategory: 'harnesses',
    petType: ['dog'],
    images: ['https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=500'],
    stock: 50,
    sku: 'DOG-ACC-003',
    brand: 'NoPull',
    rating: 4.7,
    featured: true,
    subscriptionEligible: false,
  },
  {
    name: 'Cat Bed - Plush & Cozy',
    description: 'Soft, plush cat bed with raised edges. Perfect for napping.',
    price: 27.99,
    category: 'accessories',
    subcategory: 'beds',
    petType: ['cat'],
    images: ['https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=500'],
    stock: 45,
    sku: 'CAT-ACC-002',
    brand: 'CozyCat',
    rating: 4.6,
    featured: false,
    subscriptionEligible: false,
  },
  {
    name: 'Dog Bed - Orthopedic',
    description: 'Orthopedic dog bed with memory foam. Supports joints and reduces pressure points.',
    price: 49.99,
    category: 'accessories',
    subcategory: 'beds',
    petType: ['dog'],
    images: ['https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=500'],
    stock: 35,
    sku: 'DOG-ACC-004',
    brand: 'ComfortBed',
    rating: 4.8,
    featured: true,
    subscriptionEligible: false,
  },
  {
    name: 'Pet ID Tag - Engraved',
    description: 'Custom engraved ID tag with your pet\'s name and phone number.',
    price: 8.99,
    category: 'accessories',
    subcategory: 'id-tags',
    petType: ['dog', 'cat'],
    images: ['https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=500'],
    stock: 200,
    sku: 'ACC-TAG-001',
    brand: 'IDSafe',
    rating: 4.5,
    featured: false,
    subscriptionEligible: false,
  },
  {
    name: 'Water Fountain - Pet Drinking',
    description: 'Automatic water fountain keeps water fresh and flowing. Encourages drinking.',
    price: 39.99,
    category: 'accessories',
    subcategory: 'bowls',
    petType: ['dog', 'cat'],
    images: ['https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=500'],
    stock: 40,
    sku: 'ACC-FOUNTAIN-001',
    brand: 'FreshFlow',
    rating: 4.7,
    featured: true,
    subscriptionEligible: false,
  },
  {
    name: 'Cat Litter Box - Covered',
    description: 'Privacy-covered litter box with odor control. Includes scoop and mat.',
    price: 32.99,
    category: 'accessories',
    subcategory: 'litter',
    petType: ['cat'],
    images: ['https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=500'],
    stock: 38,
    sku: 'CAT-ACC-003',
    brand: 'PrivacyBox',
    rating: 4.5,
    featured: false,
    subscriptionEligible: false,
  },
  {
    name: 'Dog Poop Bag Dispenser - Refillable',
    description: 'Convenient dispenser with biodegradable bags. Attaches to leash.',
    price: 6.99,
    category: 'accessories',
    subcategory: 'cleanup',
    petType: ['dog'],
    images: ['https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=500'],
    stock: 150,
    sku: 'DOG-ACC-005',
    brand: 'CleanWalk',
    rating: 4.6,
    featured: false,
    subscriptionEligible: false,
  },
];

async function seedProducts() {
  try {
    const mongoUri = process.env.MONGODB_URI;
    
    if (!mongoUri) {
      console.error('❌ MONGODB_URI not found in .env.local file!');
      console.error('Please make sure .env.local exists and contains MONGODB_URI');
      process.exit(1);
    }

    console.log('Connecting to MongoDB...');
    await mongoose.connect(mongoUri);
    console.log('✅ Connected to MongoDB');

    // Clear existing products
    const deleted = await Product.deleteMany({});
    console.log(`Cleared ${deleted.deletedCount} existing products`);

    // Insert sample products
    console.log('Inserting products...');
    const inserted = await Product.insertMany(sampleProducts);
    console.log(`✅ Successfully seeded ${inserted.length} products!`);

    await mongoose.disconnect();
    console.log('Disconnected from MongoDB');
    process.exit(0);
  } catch (error) {
    console.error('❌ Error seeding products:', error.message);
    process.exit(1);
  }
}

seedProducts();
